### PR TITLE
Use built-in  node inspector instead of node-inspector

### PR DESCRIPTION
**Pull request by zamotany**
Fixes: #322

Review and merge this after #437 is merged.

### CODE REVIEW

**Comment by toddw** [comment]
Running `npm run debug` results in 24 tests failing… They all seem to fail with the same error message
> only one instance of babel-polyfill is allowed

**Comment by zamotany** [comment]
@toddw currently you can debug only one test at once:
```
nom run debug <path/to/test>
```
I wrote quick note about it in `README.md`.

This is a known issue when debugging all tests at once, but currently I ran out of ideas how to fix it. Nevertheless limitation to debug only one test at once is somewhat logical and improves performance, since there is no need to wait for other tests to finish.

I suggest to leave this limitation for now and see in practice if option to debug all tests at once is actually needed and then take care of it.

**Comment by toddw** [comment]
:+1:

**Comment by toddw** [comment]
Made a couple updates here: https://github.com/TrueCar/gluestick/pull/453

**Pull request merged**
