### PR TITLE
Upgrade to Node v6

### LINKED ISSUE #134: Upgrade to Node v6.0.0
We also want to lock the Docker file at node: 6 to prevent unexpected failures. From then on, we will test Node versions prior to upgrading the version in the Docker file.

### PR DESCRIPTION
**Pull request by christinebrass**
Closes #134
- Lock the Docker file down to Node v6
- Upgrade node-sass and pm2 to resolve issues with the updated version

### CODE REVIEW

**Comment by toddw** [comment]
There were some issues with [node-inspector](https://github.com/node-inspector/node-inspector)'s 3rd party dependency [v8-profiler](https://github.com/node-inspector/v8-profiler): https://github.com/node-inspector/v8-profiler/issues/89

Do we need to update `node-inspector` as well?

**Comment by christinebrass** [comment]
Possibly. Thanks for pointing that out, I'll look into that.

**Comment by christinebrass** [comment]
@toddw I tested with a complete wipe & re-install of Node v6, and didn't find any issues aside from some deprecation notices. I was able to generate a new Gluestick project and run successfully.

**Comment by toddw** [comment]
:+1:

**Pull request merged**
