### PR TITLE
Support dismissible error overlay + various tweaks

### PR DESCRIPTION
**Pull request by zamotany**

### CODE REVIEW

**Comment by toddw** [comment]
As we discussed we should add something to the gluestick config to enable/disable this functionality. I would have it on by default but with the option to turn it off.

**Comment by threehams** [comment]
I'm not sure if this is covered by this PR, but if there's an in-flight async action which triggers a re-render of a component after ErrorOverlay shows, the result is a _very_ confusing error:

The warning:
```
errorUtils.js?10fa:86 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Landing`. See https://fb.me/react-warning-keys for more information.
    in Link (created by Landing)
```

The next error is repeated over 800 times:
```
errorUtils.js?10fa:86 Warning: _renderNewRootComponent(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate. Check the render method of Landing.

console.error | @ | errorUtils.js?10fa:86
-- | -- | --
  | printWarning | @ | warning.js?6327:33
  | warning | @ | warning.js?6327:57
  | _renderNewRootComponent | @ | ReactMount.js?0cc2:309
  | _renderSubtreeIntoContainer | @ | ReactMount.js?0cc2:401
  | render | @ | ReactMount.js?0cc2:422
  | crash | @ | errorUtils.js?10fa:63
  | console.error | @ | errorUtils.js?10fa:87
  | printWarning | @ | warning.js?6327:33
  | warning | @ | warning.js?6327:57
  | validateExplicitKey | @ | ReactElementValidator.js?f652:93
  | validateChildKeys | @ | ReactElementValidator.js?f652:113
  | createElement | @ | ReactElementValidator.js?f652:190
  | patchedCreateElement | @ | patch.dev.js?c9a2:188
  | Landing | @ | Landing.js?36bd:28
  | instantiate | @ | createClassProxy.js?8681:91


```

**Comment by zamotany** [comment]
@threehams I cannot reproduce it. Can you elaborate or provide some examples?

**Review by toddw — APPROVED** [review]
:+1: can we get a release out with this?

**Pull request merged**
