### PR TITLE
Make a better home example

### PR DESCRIPTION
**Pull request by dratwas**
Solves #460 
Now it looks like this:
screen shot 2017-02-28 at 14 20 03

In this PR I added alias called `compiled` for assets which are loaded from node_modules. I did it because universal-webpack loads assets from node_modules as .js files until those files aren't added to `exclude_from_externals` array.
Check:
https://github.com/halt-hammerzeit/universal-webpack/blob/master/README.md#advanced-configuration

We don't know which libraries/assets user want to load from node_modules so instead of adding it to `exclude_from_externals` we can use a alias which is set to node_modules path.

Now for loading i.e. normalize.css:
```javascript
import 'compiled/normalize.css';
```

### CODE REVIEW

**Review by ferrannp — COMMENTED** [review]
What do you think of making it mobile friendly @dratwas ? I think we would just need the last row to be of 1 column instead on 3 on smaller screens.

**Review by ferrannp — CHANGES_REQUESTED** [review]
Let's request the change so it is clearer to track it.

**Comment by dratwas** [comment]
@ferrannp I made it mobile friendly in last commit.

**Review by ferrannp — CHANGES_REQUESTED** [review]
- Fonts are not looking good in header and other places
- Header should has no margin

**Pull request merged**
