### PR TITLE
Add Gluestick prefix to logging statements

### PR DESCRIPTION
**Pull request by christinebrass**
So that users know where the logging statements are originating from:

logger

### CODE REVIEW

**Comment by webmanarmy** [comment]
This is great! Can we change it to `[GlueStick]`?

**Comment by toddw** [comment]
This is great! Can we change it to [GlueStick]?

**Comment by christinebrass** [comment]
Done! 😄

**Comment by toddw** [comment]
:+1: Will merge as soon as build passes

**Pull request merged**
