### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/TrueCar/gluestick/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/TrueCar/gluestick).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by sethbattin** [comment]
Looks like there are a few invalid alerts in https://lgtm.com/projects/g/TrueCar/gluestick/alerts?mode=list. 
For example `Comparison between inconvertible types` claiming that `RegExp.exec` returns a boolean.  Another alert is `Unused variable React`, which is invalid because that file contains jsx and needs React available.

There are some others in there that appear to be candidates for lint checks.

**Comment by xcorail** [comment]
Hi @sethbattin 

Thanks a lot for the feedback and the report of false positives ... I'll have a look right away.

**Comment by xcorail** [comment]
Hello @sethbattin 

I found only one `Comparison between inconvertible types`, [here](https://lgtm.com/projects/g/TrueCar/gluestick/alerts/?mode=tree&ruleFocus=4860077). Is that the one you are looking at? When you hover on the alert (the giant red box), it highlights the expression it refers to. It's `!pathMatch.length`. This one is a boolean, because of the `!`, and you compare it to a number, with `===`. This will always be false.

**Comment by sethbattin** [comment]
Ah, my mistake, that certainly is an error.

**Comment by xcorail** [comment]
Also a UX problem on our side ... we could certainly improve the message by saying `Expression !pathMatch.length` instead of `This expression`

**Comment by xcorail** [comment]
Hi @sethbattin 

Just to let you know that we have fixed the `Unused variable React` false positive, with this [PR](https://github.com/Semmle/ql/pull/557). The fix will be available in lgtm.com in a few days.

**Thanks again for reporting it!**

Cheers

**Pull request closed without merging**
