### PR TITLE
mv … '/etc/resolv.conf': Device or resource busy

### PR DESCRIPTION
**Pull request by dratwas**
Work around /etc/resolve.conf being locked down by using `cat` instead

### CODE REVIEW

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check][clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Comment by dratwas** [comment]
[clabot:check]

**Review by ferrannp — APPROVED** [review]

**Pull request merged**
