### PR TITLE
Refactor test suite to Jest (+watch +coverage)

### PR DESCRIPTION
**Pull request by ferrannp**
Related to #406 

- All tests from `test` folder are now using Jest and they only depend on it (no `sinon`, no `expect`). There is a configuration in `package.json` to tell Jest only run tests inside `test` folder
- `--watch` mode is working (see gif below)
- Running `npm run test-coverage` will create html page into `coverage` folder (so it also solves #345)
- Debugging with Chrome, just need to follow these steps: https://facebook.github.io/jest/docs/troubleshooting.html#tests-are-failing-and-you-don-t-know-why 

This is a pull request to get familiar also with Jest and play with it (specially with the `--watch` mode). If we are happy with it, we could also introduce Jest to the generated app with gluestick so we can get rid of `istambul` (solving #333), `mocha`, `karma`, `sinon` and `expect` (maybe even more if we needed special `babel` deps for it).

## Watch mode

watch

## Debugging

screen shot 2017-01-20 at 17 53 11

screen shot 2017-01-20 at 17 53 16

### CODE REVIEW

**Comment by sethbattin** [comment]
Followon from #322 : my first thought is this:  https://youtrack.jetbrains.com/issue/WEB-14979 <- jest does not have direct webstorm support yet.  :|

But that's really just ide-sugar anyway.  As long as there is a cli entry point and file saving triggers watch mode, then we're good regardless of explicit support.  And if debugging via devtools works, then that solves the other use case.

I will try this one out in earnest later in the day.

**Comment by zamotany** [comment]
>Debugging with Chrome, just need to follow these steps: https://facebook.github.io/jest/docs/troubleshooting.html#tests-are-failing-and-you-don-t-know-why

They use `node-inspector` but we are removing it in favour of `node --inspect` (#322).

**Comment by zamotany** [comment]
https://youtu.be/1cfA87h_1hI
on Ubuntu 16.04

Notice that `debugger;` statement in test **doesn't** trigger break.

**Comment by toddw** [comment]
This looks really cool!

Looks like there are some issues in the build: https://travis-ci.org/TrueCar/gluestick/builds/193784640#L387

**Comment by toddw** [comment]
The tests are broken specifically when `--watch` is passed so it is likely something that just needs to be updated in our tests

**Comment by ferrannp** [comment]
All test seem to `PASS` but for some reason the build gets stuck (not exiting with error or success). I am not sure if those console.error(s) or some throwings that are happening in some tests are the cause. I need to investigate/try more on this.

---
Edit 1:

Ok, I found that the test that makes Travis to fail is `new.test.js`, that tests promts the user to a question `Do you wish to continue?` and this keeps Jest to be hanging. I need to investigate a solution for this.

The other thing that concerns me is that all these tests are actually hitting the disk and creating/removing files. Probably, we want unit tests to mock this behaviour. See the exact example with `fs` https://facebook.github.io/jest/docs/manual-mocks.html

---
Edit 2:

Ok I have the build passing: https://travis-ci.org/TrueCar/gluestick/builds/194489121

The problem is that I had to run it manually since it looks like that PRs to `TrueCar:v1` are not triggering builds in Travis. Can you check this @toddw? I guess it is just to change `travis.yml` in `develop`.

**Comment by toddw** [comment]
I updated _.travis.yml_ so it should now include the `v1` branch

**Comment by toddw** [comment]
> The other thing that concerns me is that all these tests are actually hitting the disk and creating/removing files. Probably, we want unit tests to mock this behaviour.

Yeah, since a major part of the CLI is creating files, it does write and read from disk during tests. I'm sure we could mock this but it might get tricky to validate the CLI is actually doing what it should. We are totally open to any suggestions here

**Comment by ferrannp** [comment]
So build is green :). About hitting the disk, I think that for now is fine. Maybe in the future we want to try something but it does not feel as a bottleneck right now. I think this PR is ready as it is @toddw.

**Comment by toddw** [comment]
works great! Thanks @ferrannp 

I was not able to get Chrome inspector to work yet but that's a different issue.
Related (https://github.com/TrueCar/gluestick/issues/406#issuecomment-274439629)

**Comment by ferrannp** [comment]
@toddw you should be able when https://github.com/TrueCar/gluestick/pull/445 is merged.

**Pull request merged**
