### PR TITLE
Fix server debug

### PR DESCRIPTION
**Pull request by zamotany**
Fixes: #639

### CODE REVIEW

**Review by ferrannp — COMMENTED** [review]
.

**Review by ferrannp — CHANGES_REQUESTED** [review]
Probably this file requires some testing?

**Comment by zamotany** [comment]
Dunno why test haven't been written when refactoring

**Comment by pawlucci** [comment]
@mike866

**Comment by michalchudziak** [comment]
I think we can merge this one and prepare proper test suite for start command at the beginning of next sprint. WDYT @ferrannp?

**Comment by ferrannp** [comment]
@mike866 yup, we can track it in a separate issue.

**Pull request merged**
