### PR TITLE
Update kefir for flow 0.50.0 compatibility

### PR DESCRIPTION
**Pull request by supergibbs**
Just part of the PR https://github.com/TrueCar/gluestick/pull/1065

### CODE REVIEW

**Comment by supergibbs** [comment]
@zamotany Is this right? I noticed in the package update commit you didn't update the yarn.lock file. Should I just update the min version in package.json instead?

**Comment by zamotany** [comment]
`package.json` is a top priority for updating dependencies, so yes.

**Comment by supergibbs** [comment]
Got it but this one actually is a dependency so the lock file is the only way to update it.

**Comment by zamotany** [comment]
I see. This is a dependency of other gluestick depdendency and we cannot really control it apart from `yarn.lock` which only works for `yarn`. So basically the flow will still detect errors if depednencies are installed with npm.

**Comment by zamotany** [comment]
`kefir` is a dependency of `flow-copy-source` so it doesn't really make sense to check it with flow, because even if it fails we don't care.

**Comment by supergibbs** [comment]
Ya, probably doesn't really matter if we're checking it or not. The dependency is set correctly though (`"kefir": "^3.2.0",`) in `flow-copy-source` so npm installs the latest version and works.

**Comment by supergibbs** [comment]
Out of date now and not really needed

**Pull request closed without merging**
