### PR TITLE
Bump loadjs to 3.2.0

### PR DESCRIPTION
**Pull request by christinebrass**
* Use new `numRetries` option and remove old retry logic
* Set `crossOrigin` attribute to properly log script errors

### CODE REVIEW

**Comment by toddw** [comment]
:+1:

**Comment by christinebrass** [comment]
Leaving this as a wip PR for now, since we should make modifications to allow the loadjs `before` function to be configured on a per-app basis via the app config.

**Comment by sethbattin** [comment]
@cybrass , I pulled the setting into consumer-frontend's PR 897.

**Comment by christinebrass** [comment]
👍

**Pull request merged**
