### PR TITLE
[ON HOLD] HappyPack integration.

### LINKED ISSUE #408: Integrate HappyPack to speed up builds
Large applications can take a really long time to build. HappyPack should help by building files in parallel. We would like to use HappyPack in our Webpack builds. https://github.com/amireh/happypack

### PR DESCRIPTION
**Pull request by michalchudziak**
Closes #408 

Now every loader uses HappyPack. It allows us to increase performance for larger builds. I've decided to let heavier loaders to run on higher number of threads, while smaller ones run on 2 threads only.

### CODE REVIEW

**Comment by toddw** [comment]
This is awesome! I can't wait to try it out in the morning on one of our large apps. I'll post the benchmark results

**Comment by toddw** [comment]
Used this branch on one of our larger apps and ran into some errors. Going to test with a new project to see if it works then figure out what we need to do to resolve the issues. It is possible the errors were app specific, possibly related to webpack-additions in that app

**Comment by toddw** [comment]
Throwing errors when generating a new project and running `NODE_ENV=production gluestick build`

Error:
```
module.js:457
    throw err;
    ^

Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/twilliams/dev/gluestick/node_modules/extract-text-webpack-plugin/loader.js:6:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by michalchudziak** [comment]
Hey, @toddw! I'm sorry that I didn't notice build command failure. 

It should be fixed now. Also, I've dropped HappyPack support for some loaders since:

We are using `OptimizeCSSAssetsPlugin` which performs very well with CSS and asset loaders, and I'm afraid that it might now work very well with HappyPack. 

Also using `json-loader` with HappyPack might result in some [issues](https://github.com/amireh/happypack/wiki/Loader-Compatibility-List).

So, I think to leave it just to speed up `babel-loader` seems like a reasonable thing.

Please let me know WDYT.

**Comment by michalchudziak** [comment]
I'd recommend waiting with merging this one due to upcoming webpack 2 integration. 

This is what HappyPack says about supporting webpack 2:

> It may, and it may not! Official support for webpack 2 will not land until webpack 2 is out of beta status. Until then, IT wouldn't hurt to try but YMMV.

I think we need to decide if we want to try it experimentally with new version of WP.

**Comment by toddw** [comment]
I'm fine with waiting until Webpack 2 comes out of beta for this PR. You can close the PR until then if you want.

**Pull request closed without merging**
